package table

import (
	"fmt"

	"github.com/forbole/bookkeeper/module/subtrate/client"
	subtratetypes "github.com/forbole/bookkeeper/module/subtrate/types"
)

/*
curl -X POST 'https://polkadot.api.subscan.io/api/scan/account/reward_slash' \
  --header 'Content-Type: application/json' \
  --header 'X-API-Key: YOUR_KEY' \
  --data-raw '{
    "row": 20,
    "page": 1,
    "address": "15fTw39Ju2jJiHeGe1fJ5DtgugUauy9tr2HZuiRNFwqnGQ1Q"
  }'
*/
// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

// curl -X POST 'https://polkadot.api.subscan.io/api/scan/account/reward_slash' \
//   --header 'Content-Type: application/json' \
//   --header 'X-API-Key: YOUR_KEY' \
//   --data-raw '{
//     "row": 20,
//     "page": 1,
//     "address": "15fTw39Ju2jJiHeGe1fJ5DtgugUauy9tr2HZuiRNFwqnGQ1Q"
//   }'

func GetRewardSum(api *client.SubscanClient, address string) (*subtratetypes.RewardSlash, error) {
	fmt.Println(api)
	requestUrl := "/api/scan/staking_history"

	type Payload struct {
		Row     int    `json:"row"`
		Page    int    `json:"page"`
		Address string `json:"address"`
	}

	payload := Payload{
		Row:     20,
		Page:    1,
		Address: address,
	}
	var rewardSlash subtratetypes.RewardSlash
	err := api.CallApi(requestUrl, payload, &rewardSlash)
	if err != nil {
		return nil, err
	}

	return &rewardSlash, nil
}
